### ISSUE TITLE
Not working with SIFT instead of OPENCV_SIFT

### ISSUE THREAD

**Issue by chekirou** [ucuapps/OpenGlue#5]
Hi, 
I would like to use `models.features.sift.SIFT` instead of `OPENCV_SIFT`as a feature extractor but the superglue matcher doesn't work with this configuration. Even if the model is trained using the features from `OPENCV_SIFT`, shoudn't the two versions of sift compute the same features given the same parameters ? Here are the configurations i used :
```
features:
  name: 'SIFT'
  descriptor_dim: 128
  parameters:
    max_keypoints: 2048
    nms_diameter: 9
    rootsift: True
    descriptor_dim: 128 
```
With `SIFT` no matches are found.
